### ISSUE TITLE
pagination

### ISSUE THREAD

**Issue by maxogden** [bionode/bionode-ncbi#2]
for e.g. http://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?&retmode=json&version=2.0&db=gds&term=GSE48968&field=ACCN&usehistory=y which has 2428 results but we can only do 1000 at a time we should implement a batched fetcher that basically paginates through all of the result ids

**Comment by bmpvieira** [comment]
I've done `bionode-ncbi search gds GSE48968 | json -ga0 uid > list1.txt` and checked against the IDs in `http://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?&retmode=json&retmax=2428&version=2.0&db=gds&term=GSE48968&field=ACCN&usehistory=y` and got exactly the same 2428 IDs. I'm still not sure why piping directly to wc gives 2427 instead of 2428, but at least pagination is working so I'm closing this.
