### ISSUE TITLE
Add Blast API

### ISSUE THREAD

**Issue by Fohlen** [bionode/bionode-ncbi#39]
Hey there. I've ported the [Blast API](https://ncbi.github.io/blast-cloud/dev/api.html) as a rudimentary example here, [ncbi-lib](https://github.com/Fohlen/ncbi-lib).
I've seen it is missing in this great NCBI library so I'd be willing to provide some help and source code to add a more feature-rich version to `bionode`

What do you guys think?

**Comment by thejmazz** [comment]
Hi @Fohlen, have you seen [bionode-blast](https://github.com/bionode/bionode-blast)?

Looks like you already [encountered](https://github.com/Fohlen/ncbi-lib/blob/992219081892195a5b3ceaae4e4e5b7b09bccf48/functions/__main__.js#L30) some of the inconveniences of the Blast API yourself :)

Perhaps take a look at bionode-blast and see if there are any differences between your approach and ours? (I actually uncompressed JSON instead of parsing XML - forget whether or not there was a real reason for doing that). Perhaps eventually your Stdlib function would just declare params and pass them through to a bionode module?

Cheers!

**Comment by Fohlen** [comment]
Hi @thejmazz 
I probably didn't see the module, because it is not included in the docs yet!
I used XML there because the `JSON2` module will create an archive to download, whereas the `XML` API makes it available directly.

Probably I could enhance the current `bionode-blast` utility 👍
